# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Set the version of Python and requirements required to build your docs
python:
  version: 3.12
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Don't build any extra formats
formats: []
